apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: devops-portfolio
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  # - service-loadbalancer.yaml  # habilite esta linha (e comente service.yaml/ingress.yaml)
  #                              # se preferir expor via LoadBalancer da OCI, sem Ingress Controller.
